Base: 
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

full_h5_DeepCrossing:
    model: DeepCrossing
    dataset_id: full_h5
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 1.e-8
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    residual_blocks: [ 64, 64, 64 ]
    dnn_activations: relu
    net_dropout: 0
    batch_norm: False
    use_residual: True
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'