Base: 
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 5
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

FM_default: # This is a config template
    model: FM
    dataset_id: full_h5
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    regularizer: 0
    batch_size: 128
    embedding_dim: 100
    epochs: 40
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'
