smadex_csv:
    data_root: ../data/
    data_format: csv    
    train_data: ../data/smadex_csv/smadex_train_example_tiny.csv
    valid_data: ../data/smadex_csv/smadex_val_example_tiny.csv
    test_data: ../data/smadex_csv/smadex_test_example_tiny.csv
    min_categr_count: 1
    feature_cols:
        [

          {name: "release_date",active: True, dtype: float, type: numeric},
          {name: "release_msrp",active: True, dtype: float, type: numeric},
          {name: "46",active: True, dtype: str, type: categorical},
          {name: "is_smartphone", active: True, dtype: str, type: categorical}

          ]
    label_col: {name: converted, dtype: float, type: categorical}